ci: enable release ci
ScaleLeap/selling-partner-api-sdk pull request #18
Opened 2021-03-12 06:51 UTC by nguyentoanit

2021-03-12 06:51 UTC, moltar commented
Task linked: [GHORG-11 Publish to NPM](https://app.clickup.com/t/2250003/GHORG-11)

2021-03-12 06:52 UTC, moltar requested changes

2021-03-12 06:52 UTC, moltar commented on package.json
> +  "version": "1.0.0",
This is not needed. Release will bump the version automatically.

2021-03-25 09:09 UTC, nguyentoanit commented
@moltar: 🚀 🚀 🚀

2021-03-25 09:11 UTC, merged